import { Box, Button, Image, Text, Link } from "@chakra-ui/react";

const Cards = () => {
  return (
    <>
      {/* Cards Section */}
      <Box
        display={"flex"}
        flexDirection={"column"}
        alignItems={"center"}
        py={"0px"}
        px={"24px"}
        gap={"32px"}
        isolation={"isolate"}
        pos={"absolute"}
        w={"600px"}
        h={"100px"}
        left={"calc(50% - 600px/2 - 318px)"}
        top={"calc(50% - 100px/2 - 170px)"}
        background={"#0A335F"}
        borderRadius={"10px"}
      >
        <Image
          src="/firstCard_icon.png"
          alt="First Card Icon"
          boxSize="86px"
          position="absolute"
          left="2px"
          top="8px"
          zIndex="5"
        />
        <Text
          position="absolute"
          width="225px"
          height="20px"
          left="98px"
          top="13px"
          fontFamily="Inter"
          fontStyle="normal"
          fontWeight="600"
          fontSize="20px"
          lineHeight="20px"
          color="#FFFFFF"
          flex="none"
          order="1"
          flexGrow="0"
          zIndex="1"
        >
          Audited smart contract
        </Text>
        <Button
          display="flex"
          flexDirection="column"
          alignItems="center"
          p="0px 24px"
          gap="32px"
          isolation="isolate"
          position="absolute"
          w="255px"
          h="36px"
          left="98px"
          top="52px"
          background="#FFFFFF"
          borderRadius="10px"
          flex="none"
          order="3"
          flexGrow="0"
          zIndex="3"
        >
          <Box
            display={"flex"}
            flexDirection={"column"}
            alignItems={"center"}
            py={"8px"}
            px={"10px"}
            gap={"32px"}
            isolation={"isolate"}
            pos={"absolute"}
            w={"30px"}
            h={"30px"}
            left={"222px"}
            top={"3px"}
            background={"#3C72AA"}
            borderRadius={"10px"}
            flex={"none"}
            order={"2"}
            flexGrow={"0"}
            zIndex={"2"}
          >
            <Box
              pos={"absolute"}
              w={"25px"}
              h={"18px"}
              left={"2px"}
              top={"6px"}
              background={`url(/copy.png) no-repeat`}
              flex={"none"}
              order={"1"}
              flexGrow={"0"}
              zIndex={"1"}
            />
          </Box>
          <Link
            href="https://idential.xyz/claim/..."
            target="_blank"
            rel="noopener noreferrer"
            pos="absolute"
            w="204px"
            h="16px"
            left="8px"
            top="10px"
            fontFamily="Inter"
            fontStyle="normal"
            fontWeight="400"
            fontSize="16px"
            lineHeight="100%"
            textDecorationLine="underline"
            color="#000000"
            flex="none"
            order="1"
            flexGrow="0"
            zIndex="1"
          >
            https://idential.xyz/claim/...
          </Link>
        </Button>
        <Link
          fontSize="12px"
          lineHeight="100%"
          fontWeight={400}
          fontFamily="Inter"
          color="#FFFFFF"
          position="absolute"
          width="54px"
          height="12px"
          left="360px"
          top="77px"
          flex="none"
          order={4}
          flexGrow={0}
          zIndex={4}
        >
          Edit page
        </Link>
        <Text
          fontFamily="Inter"
          fontStyle="normal"
          fontWeight="500"
          fontSize="50px"
          lineHeight="50px"
          color="#FFFFFF"
          position="absolute"
          width="104px"
          height="43px"
          left="475px"
          top="26px"
          order={2}
          flexGrow={0}
          zIndex={2}
        >
          425
        </Text>
      </Box>
      <Box
        display={"flex"}
        flexDirection={"column"}
        alignItems={"center"}
        py={"0px"}
        px={"24px"}
        gap={"32px"}
        isolation={"isolate"}
        pos={"absolute"}
        w={"600px"}
        h={"100px"}
        left={"calc(50% - 600px/2 + 318px)"}
        top={"calc(50% - 100px/2 - 170px)"}
        background={"#0A335F"}
        borderRadius={"10px"}
      >
        <Image
          src="/secondCard_icon.png"
          boxSize="80px"
          borderRadius="10px"
          position="absolute"
          left="9px"
          top="10px"
          zIndex={6}
        />
        <Text
          position="absolute"
          width="267px"
          height="20px"
          left="98px"
          top="13px"
          fontFamily="Inter"
          fontStyle="normal"
          fontWeight="600"
          fontSize="20px"
          lineHeight="20px"
          color="#FFFFFF"
          flex="none"
          order="1"
          flexGrow="0"
          zIndex="1"
        >
          Spearbit security workshop
        </Text>
        <Text
          fontFamily="Inter"
          fontStyle="normal"
          fontWeight="500"
          fontSize="50px"
          lineHeight="50px"
          color="#FFFFFF"
          position="absolute"
          width="104px"
          height="43px"
          left="475px"
          top="26px"
          order={2}
          flexGrow={0}
          zIndex={2}
        >
          344
        </Text>
        <Button
          display="flex"
          flexDirection="column"
          alignItems="center"
          p="0px 24px"
          gap="32px"
          isolation="isolate"
          position="absolute"
          w="255px"
          h="36px"
          left="98px"
          top="52px"
          background="#FFFFFF"
          borderRadius="10px"
          flex="none"
          order="3"
          flexGrow="0"
          zIndex="3"
        >
          <Box
            display={"flex"}
            flexDirection={"column"}
            alignItems={"center"}
            py={"8px"}
            px={"10px"}
            gap={"32px"}
            isolation={"isolate"}
            pos={"absolute"}
            w={"30px"}
            h={"30px"}
            left={"222px"}
            top={"3px"}
            background={"#3C72AA"}
            borderRadius={"10px"}
            flex={"none"}
            order={"2"}
            flexGrow={"0"}
            zIndex={"2"}
          >
            <Box
              pos={"absolute"}
              w={"25px"}
              h={"18px"}
              left={"2px"}
              top={"6px"}
              background={`url(/copy.png) no-repeat`}
              flex={"none"}
              order={"1"}
              flexGrow={"0"}
              zIndex={"1"}
            />
          </Box>
          <Link
            href="https://idential.xyz/claim/..."
            target="_blank"
            rel="noopener noreferrer"
            pos="absolute"
            w="204px"
            h="16px"
            left="8px"
            top="10px"
            fontFamily="Inter"
            fontStyle="normal"
            fontWeight="400"
            fontSize="16px"
            lineHeight="100%"
            textDecorationLine="underline"
            color="#000000"
            flex="none"
            order="1"
            flexGrow="0"
            zIndex="1"
          >
            https://idential.xyz/claim/...
          </Link>
        </Button>
        <Link
          fontSize="12px"
          lineHeight="100%"
          fontWeight={400}
          fontFamily="Inter"
          color="#FFFFFF"
          position="absolute"
          width="54px"
          height="12px"
          left="360px"
          top="77px"
          flex="none"
          order={4}
          flexGrow={0}
          zIndex={4}
        >
          Edit page
        </Link>
      </Box>
      <Box
        display={"flex"}
        flexDirection={"column"}
        alignItems={"center"}
        py={"0px"}
        px={"24px"}
        gap={"32px"}
        isolation={"isolate"}
        pos={"absolute"}
        w={"600px"}
        h={"100px"}
        left={"calc(50% - 600px/2 - 318px)"}
        top={"calc(50% - 100px/2 - 48px)"}
        background={"#0A335F"}
        borderRadius={"10px"}
      >
        <Image
          src="/thirdCard_icon.png"
          borderRadius="10px"
          w="80px"
          h="80px"
          pos="absolute"
          left="11px"
          top="10px"
          order={1}
          zIndex={1}
        />
        <Text
          position="absolute"
          width="285px"
          height="20px"
          left="98px"
          top="13px"
          fontFamily="Inter"
          fontStyle="normal"
          fontWeight="600"
          fontSize="20px"
          lineHeight="20px"
          color="#FFFFFF"
          flex="none"
          order="1"
          flexGrow="0"
          zIndex="1"
        >
          Attended Spearbit hackathon
        </Text>
        <Text
          fontFamily="Inter"
          fontStyle="normal"
          fontWeight="500"
          fontSize="50px"
          lineHeight="50px"
          color="#FFFFFF"
          position="absolute"
          width="104px"
          height="43px"
          left="475px"
          top="26px"
          order={2}
          flexGrow={0}
          zIndex={2}
        >
          236
        </Text>
        <Button
          display="flex"
          flexDirection="column"
          alignItems="center"
          p="0px 24px"
          gap="32px"
          isolation="isolate"
          position="absolute"
          w="255px"
          h="36px"
          left="98px"
          top="52px"
          background="#FFFFFF"
          borderRadius="10px"
          flex="none"
          order="3"
          flexGrow="0"
          zIndex="3"
        >
          <Box
            display={"flex"}
            flexDirection={"column"}
            alignItems={"center"}
            py={"8px"}
            px={"10px"}
            gap={"32px"}
            isolation={"isolate"}
            pos={"absolute"}
            w={"30px"}
            h={"30px"}
            left={"222px"}
            top={"3px"}
            background={"#3C72AA"}
            borderRadius={"10px"}
            flex={"none"}
            order={"2"}
            flexGrow={"0"}
            zIndex={"2"}
          >
            <Box
              pos={"absolute"}
              w={"25px"}
              h={"18px"}
              left={"2px"}
              top={"6px"}
              background={`url(/copy.png) no-repeat`}
              flex={"none"}
              order={"1"}
              flexGrow={"0"}
              zIndex={"1"}
            />
          </Box>
          <Link
            href="https://idential.xyz/claim/..."
            target="_blank"
            rel="noopener noreferrer"
            pos="absolute"
            w="204px"
            h="16px"
            left="8px"
            top="10px"
            fontFamily="Inter"
            fontStyle="normal"
            fontWeight="400"
            fontSize="16px"
            lineHeight="100%"
            textDecorationLine="underline"
            color="#000000"
            flex="none"
            order="1"
            flexGrow="0"
            zIndex="1"
          >
            https://idential.xyz/claim/...
          </Link>
        </Button>
        <Link
          fontSize="12px"
          lineHeight="100%"
          fontWeight={400}
          fontFamily="Inter"
          color="#FFFFFF"
          position="absolute"
          width="54px"
          height="12px"
          left="360px"
          top="77px"
          flex="none"
          order={4}
          flexGrow={0}
          zIndex={4}
        >
          Edit page
        </Link>
      </Box>
    </>
  );
};

export default Cards;
